language: perl
perl:
  - "5.8"
  - "5.20"
  - "5.22"
  - "5.24"
  - "5.26"
  - "5.28"
matrix:
  include:
    - perl: 5.28
      env: "COVERAGE=1 TEST_VERBOSE=1"
before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto
